# Generated by Django 3.0.8 on 2020-11-08 05:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_terima', models.DateField(default=datetime.date.today, null=True)),
                ('dari_atau_ke', models.CharField(max_length=500, null=True)),
                ('no_surat', models.CharField(max_length=200, null=True)),
                ('tanggal_surat', models.DateField(default=datetime.date.today, null=True)),
                ('hari_jam', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('tempat', models.CharField(max_length=500, null=True)),
                ('acara', models.TextField(null=True)),
                ('keterangan', models.TextField(null=True)),
                ('date_input', models.DateTimeField(auto_now_add=True, null=True)),
                ('kategori', models.CharField(choices=[('Surat Masuk', 'Surat Masuk'), ('Surat Keluar', 'Surat Keluar')], max_length=200, null=True)),
                ('uploaded_file', models.FileField(null=True, upload_to='')),
                ('timestamp_lastupdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
